### ISSUE TITLE
Update project for new Extension convensions

### ISSUE THREAD

**Issue by Matticusau** [Matticusau/sqlops-widgets#16]
The SQL Ops Studio extension support is now official. Need to update this project to move to the new format.

Reference: [Kevin Cunnane - Writing a SQL Operations Studio Extension in 15 minutes](https://medium.com/@kevcunnane/writing-a-sql-operations-studio-extension-in-15-minutes-7dfd24a74dfe)

**Comment by kevcunnane** [comment]
Looking forward to seeing this in the gallery. Take a look at the sp_whoisactive and Server reports samples for how to add a dedicated section for your insights. 

[Server reports](https://github.com/Microsoft/sqlopsstudio/blob/master/samples/serverReports/package.json)
- this adds a single tab for the each “report”. 
- working this way each of your insight collections would be separate tabs. 

[sp_whoisactive](https://github.com/Microsoft/sqlopsstudio/blob/master/samples/sp_whoIsActive/package.json)
- this has a tab with multiple inner sections. 
- working this way you would provide a single tab, with inner sections for each different insight collection 
- the only challenge is it assumes you have icons. Maybe create an issue if you run into problems with this

Also note the [generator-sqlops](https://www.npmjs.com/package/generator-sqlops) tool will help create the correct package.json format if you create a project using it and choose “dashboard insight” as the type. 

Best of luck!

**Comment by Matticusau** [comment]
Thanks so much for the tips @kevcunnane definitely helped and appreciate the further communication we have had. For now I took the approach of a single tab per insight, but broken into separate extensions. With what I have planned though being able to add inner sections like the sp_whoisactive is going to be a great help.
