### ISSUE TITLE
Publish project to SqlOps Marketplace 

### ISSUE THREAD

**Issue by Matticusau** [Matticusau/sqlops-widgets#17]
Now that the extension support and marketplace is complete in SqlOps Studio we can publish the extension to the marketplace.

Reference: [Kevin Cunnane - Publishing an extension for SQL Operations Studio](https://medium.com/@kevcunnane/publishing-an-extension-for-sql-operations-studio-f5a5b323c13b)

**Comment by yualan** [comment]
Hi Matt, if you run into any issues, feel free to email me at alayu@microsoft.com and we can set up a call with a few of our engineers to help unblock. Thanks for contributing!

**Comment by Matticusau** [comment]
Appreciate the offer @yualan didn't have any issues but I decided for the sake of the project life cycle management to break this into three separate extensions. Makes sense functionally as well because people may only want one and not others. That was how my original thoughts were when I built this project anyway, but at the time I could treat them as separate under the one project and install via a script ;)

Anyway check out the following projects:
- [sqlops-alwayson-insights](https://github.com/Matticusau/sqlops-alwayson-insights)
- [sqlops-mssql-instance-insights](https://github.com/Matticusau/sqlops-mssql-instance-insights)
- [sqlops-mssql-db-insights](https://github.com/Matticusau/sqlops-mssql-db-insights)
